name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/backend-ci.yml"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    uses: ./.github/workflows/backend-ci.yml
