name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/frontend-ci.yml"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  frontend-checks:
    uses: ./.github/workflows/frontend-ci.yml
